baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'My Projects - Documentation Hub'
theme = 'hugo-book'

[params]
  BookSection = '/'
  BookRepo = 'https://github.com/emmalone/my-projects'
  BookSearch = true
  BookToC = true
  BookComments = false
  BookMenuBundle = '/menu'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
